### ISSUE TITLE
Checklist for publishing this stuff on the package repository

### ISSUE THREAD

**Issue by parnikkapore** [parnikkapore/rkt-pnkp#1]
Referencing https://docs.racket-lang.org/pkg/getting-started.html...
- [ ] info.rkt and package datastructures
- [x] Documentation
- [x] Tests (and more of them)
- [x] Maaaybe come up with a witty name for this package that's not mine?
